const express=require('express')
const app=express()
const mongoose = require('mongoose')
const parkingRouter=require('./routes/parking')
mongoose.connect('mongodb://localhost/parking',{useNewUrlParser:true,useUnifiedTopology:true})
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use(parkingRouter)
app.listen(5000, () =>console.log("server up and running"))